# Starter pipeline

stages:
- stage: 'YAML_For_Testing'
  displayName: 'Testing'

  jobs:
  - job: 'First_Job'
    displayName: 'First_Job Diplay_Name'
    pool:
      name: Default
    steps:
    - script: echo Hello, world!
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
    
  - job: 'Second_Job'
    displayName: 'Second_Job Diplay_Name'
    pool:
      name: Default
    steps:
    - script: echo Hello, world!
  
