# Starter pipeline

stages:
- stage: 'YAML_For_Testing'
  displayName: 'Testing'

  jobs:
  - job: 'Second_Job'
    displayName: 'Second_Job Diplay_Name'
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'http://example.com'
        method: 'POST'
        waitForCompletion: 'true'
  
