# Starter pipeline

stages:
- stage: 'YAML_For_Testing'
  displayName: 'Testing'

  jobs:
  - job: 'First_Job'
    displayName: 'First_Job Diplay_Name'
    pool:
      name: Default
    steps:
    - script: echo Hello, world! First_Job
    
  - job: 'Second_Job'
    displayName: 'Second_Job Diplay_Name'
    dependsOn: 'First_Job'
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'ExampleGeneric'
        method: 'GET'
        waitForCompletion: 'false'
